//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angularjs2MVC_Event.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public decimal Id { get; set; }
        public string EventName { get; set; }
        public string Description { get; set; }
        public string EventDate { get; set; }
        public string Venue { get; set; }
    }
}
